[package]
name = "nine_lives"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"

# This line links our main application to its logic crate.
nine_lives_logic = { path = "nine_lives_logic" }
