# nine_lives/Cargo.toml
[workspace]
members = [
    "nine_lives_core",
    "nine_lives_ui", 
    "nine_lives_controller",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.16.1", default-features = false }
