[package]
name = "nine_lives_controller"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nine_lives"
path = "src/main.rs"

[dependencies]
bevy = "0.16.1"
nine_lives_core = { path = "../nine_lives_core" }
nine_lives_ui = { path = "../nine_lives_ui" }
